### ISSUE TITLE
How to finetune the DRA model ?

### ISSUE THREAD

**Issue by ZhihaoWu95** [alibaba/easyrobust#5]
I want to implement the DRA to a new model, but I cannot find the codes that finetune the origin model .

**Comment by JiweiTian** [comment]
I also have the same question.

**Comment by ZY123-GOOD** [comment]
Thank you for your interest in our work.
Firstly, our method can successfully attack a real-world computer vision system (including the Google Cloud Vision API). Considering the potential ethical issues and social impacts, we have not given more models and codes to obtain a new model.
Second, from an academic point of view, we believe that the provided code can reproduce the experimental results and compare them with the newly proposed attack methods. You can download these models and compare the performance with your method.
Third, after the internal ethical review and confirmation that it will not cause a negative social impact, we will further open up the training methods.
You can email me ( ee_zhuy@zju.edu.cn ) for further discussion about adversarial transferability.

**Comment by ZY123-GOOD** [comment]
I appreciate your interest in our work. Due to ethical safety, we have not shared our codes for training to avoid malicious usage from attackers.
Below, we found an interesting implementation of our paper in GitHub. Thanks to the authors of this project.
https://github.com/JerryMazeyu/DRA-BlackBoxAttack
